-- MySQL Script generated by MySQL Workbench
-- Mon Oct 18 17:37:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoUsuario` (
  `TipoUsuarioId` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`TipoUsuarioId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadoUsuario` (
  `EstadoUsuarioId` INT NOT NULL,
  `EstadoUsuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`EstadoUsuarioId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `UsuarioId` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(100) NOT NULL,
  `Paterno` VARCHAR(100) NULL,
  `Materno` VARCHAR(100) NULL,
  `TipoUsuario` INT NOT NULL,
  `EstadoUsuario` INT NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `FechaRegistro` DATETIME NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`UsuarioId`),
  INDEX `FK_TipoUsuario_TipoUsuarioId_idx` (`TipoUsuario` ASC) VISIBLE,
  INDEX `FK_EstadoUsuario_EstadoUsuarioId_idx` (`EstadoUsuario` ASC) VISIBLE,
  CONSTRAINT `FK_TipoUsuario_TipoUsuarioId`
    FOREIGN KEY (`TipoUsuario`)
    REFERENCES `mydb`.`TipoUsuario` (`TipoUsuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_EstadoUsuario_EstadoUsuarioId`
    FOREIGN KEY (`EstadoUsuario`)
    REFERENCES `mydb`.`EstadoUsuario` (`EstadoUsuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SesionUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SesionUsuario` (
  `UsuarioId` INT NOT NULL,
  `Contrasena` VARCHAR(100) NOT NULL,
  `Sesion` NVARCHAR(100) NOT NULL,
  `IntentosFallidos` INT NOT NULL DEFAULT 0,
  INDEX `FK_SesionUsuario_Usuario_idx` (`UsuarioId` ASC) VISIBLE,
  CONSTRAINT `FK_SesionUsuario_Usuario`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `mydb`.`Usuario` (`UsuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoInventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadoInventario` (
  `EstadoInventarioId` INT NOT NULL,
  `EstadoInventario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`EstadoInventarioId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `ProveedorId` INT NOT NULL,
  `RazonSocial` VARCHAR(150) NOT NULL,
  `MarcaComercial` VARCHAR(200) NULL,
  `RFC` VARCHAR(13) NULL,
  `Direccion` VARCHAR(150) NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `TelefonoAlternativo` VARCHAR(45) NULL,
  `NombreContacto` VARCHAR(100) NULL,
  `Descripcion` VARCHAR(200) NULL,
  `Notas` VARCHAR(500) NULL,
  PRIMARY KEY (`ProveedorId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `InventarioId` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Costo` DOUBLE NOT NULL,
  `PrecioVenta` DOUBLE NOT NULL,
  `Existencias` INT NOT NULL,
  `Estado` INT NOT NULL,
  `Proveedor` INT NOT NULL,
  `FechaCompra` DATETIME NOT NULL,
  PRIMARY KEY (`InventarioId`),
  INDEX `FK_EstadoInventario_EstadoInventarioID_idx` (`Estado` ASC) VISIBLE,
  INDEX `FK_ProveedorId_Proveedor_idx` (`Proveedor` ASC) VISIBLE,
  CONSTRAINT `FK_EstadoInventario_EstadoInventarioID`
    FOREIGN KEY (`Estado`)
    REFERENCES `mydb`.`EstadoInventario` (`EstadoInventarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ProveedorId_Proveedor`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `mydb`.`Proveedor` (`ProveedorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Imagenes` (
  `ImagenId` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `RutaFisica` VARCHAR(45) NOT NULL,
  `InventarioId` INT NOT NULL,
  PRIMARY KEY (`ImagenId`),
  INDEX `FK_Inventario_InventarioId_idx` (`InventarioId` ASC) VISIBLE,
  CONSTRAINT `FK_Inventario_InventarioId`
    FOREIGN KEY (`InventarioId`)
    REFERENCES `mydb`.`Inventario` (`InventarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoAlerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoAlerta` (
  `TipoAlertaId` INT NOT NULL,
  `DescripcionAlerta` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`TipoAlertaId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoAlerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadoAlerta` (
  `EstadoAlertaId` INT NOT NULL,
  `EstadoAlerta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EstadoAlertaId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alerta` (
  `AlertaId` INT NOT NULL,
  `Mensaje` VARCHAR(200) NOT NULL,
  `EstadoId` INT NOT NULL,
  `TipoAlertaId` INT NOT NULL,
  `FechaAlerta` DATETIME NOT NULL,
  `FechaCambioEstado` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`AlertaId`),
  INDEX `FK_TipoAlerta_TipoAlertaId_idx` (`TipoAlertaId` ASC) VISIBLE,
  INDEX `FK_EstadoAlerta_EstadoAlertaId_idx` (`EstadoId` ASC) VISIBLE,
  CONSTRAINT `FK_TipoAlerta_TipoAlertaId`
    FOREIGN KEY (`TipoAlertaId`)
    REFERENCES `mydb`.`TipoAlerta` (`TipoAlertaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_EstadoAlerta_EstadoAlertaId`
    FOREIGN KEY (`EstadoId`)
    REFERENCES `mydb`.`EstadoAlerta` (`EstadoAlertaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
